Configuration:
  status: warn

  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      #测试：-Dlog.level.console=warn -Dlog.level.platform=trace
      #生产：-Dlog.level.console=warn -Dlog.level.platform=info      
      - name: log.level.console
        value: trace
      - name: log.level.platform
        value: debug
      - name: log.path
        value: /var/log/zx_dms
      - name: project.name
        value: dms
  
  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      Filters:
        ThresholdFilter:
          level: info # “sys:”表示：如果VM参数中没指定这个变量值，则使用本文件中定义的缺省全局变量值
          onMatch: ACCEPT
          onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
    RollingFile: # 输出到文件，超过128MB归档
      - name: ROLLING_FILE
        ignoreExceptions: false
        #fileName: ${log.path}/dms.log
        fileName: ${log.path}/dms.log
        filePattern: "${log.path}/$${date:yyyy-MM}/dms-%d{yyyy-MM-dd}-%i.log.gz"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
        Filters:
          ThresholdFilter:
            - level: info
              onMatch: ACCEPT
              onMismatch: DENY
        Policies:
          SizeBasedTriggeringPolicy:
            size: "16 MB"
        DefaultRolloverStrategy:
          max: 3

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
    Logger: # 为包配置特殊的Log级别，方便调试
      - name: com.zx
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
  
